server:
  port: 10001

spring:
  devtools:
    restart:
      enabled: true

---
#mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "mysql-url"
    username: "username"
    password: "password"

    # 连接池配置
    druid:
      initial-size: 2
      max-active: 10
      min-idle: 1
      max-wait: 2000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1

      filters: stat,wall,slf4j

      #
      stat-view-servlet:
        enabled: true
        login-username: ""
        login-password: ""
        url-pattern: /druid/*
        reset-enable: false
        allow: 127.0.0.1
        # deny:

      #
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 100

---
# Redis
spring:
  data:
    redis:
      host: "ip"
      port: "port"
      password: "pass"
      database: 0

---
# MAIL
spring:
  mail:
    host: "host"
    protocol: smtp
    default-encoding: UTF-8
    username: "meiyou"
    password: "meiyou"
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

---
# MyBatis-Plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 主键类型
      id-type: auto
  # classpath* 会查找所有模块，如果不添加 '*' 的话，只能匹配当前模块的classpath
  mapper-locations: classpath*:mapperXml/*.xml

---
#jwt
jwt:
  signing:
    key: "meiyou"


# knife4j
knife4j:
  enable: true
  openapi:
    title: Knife4j 文档